name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-backend:
    name: Lint & type-check backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: implantdetect-backend/requirements.txt

      - name: Install dependencies
        run: |
          pip install ruff mypy
          pip install implantdetect-shared/
          pip install -r implantdetect-backend/requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Ruff lint
        run: ruff check implantdetect-backend/ implantdetect-prediction/ implantdetect-shared/

      - name: Ruff format check
        run: ruff format --check implantdetect-backend/ implantdetect-prediction/ implantdetect-shared/

      - name: Mypy (backend)
        run: mypy .
        working-directory: ${{ github.workspace }}/implantdetect-backend

      - name: Mypy (prediction)
        run: mypy .
        working-directory: ${{ github.workspace }}/implantdetect-prediction

      - name: Mypy (shared)
        run: mypy .
        working-directory: ${{ github.workspace }}/implantdetect-shared

  lint-frontend:
    name: Lint frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v7
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: implantdetect-frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: implantdetect-frontend

      - name: ESLint
        run: npm run lint
        working-directory: implantdetect-frontend

  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: docker/setup-buildx-action@v4

      - name: Build api
        uses: docker/build-push-action@v7
        with:
          context: .
          file: implantdetect-backend/Dockerfile
          push: false
          cache-from: type=gha,scope=api
          cache-to: type=gha,mode=max,scope=api

      # Removido devido a dependência do modelo, que é muito grande para o cache do GitHub Actions. O build da previsão será feito localmente.
      
      # - name: Build prediction
      #   uses: docker/build-push-action@v7
      #   with:
      #     context: .
      #     file: implantdetect-prediction/Dockerfile
      #     push: false
      #     cache-from: type=gha,scope=prediction
      #     cache-to: type=gha,mode=max,scope=prediction

      - name: Build frontend
        uses: docker/build-push-action@v7
        with:
          context: implantdetect-frontend
          file: implantdetect-frontend/Dockerfile
          push: false
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend
